/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.tquadrat.foundation.gradle.gitpublisher

import org.gradle.testkit.runner.GradleRunner
import spock.lang.Specification
import spock.lang.TempDir

/**
 * A simple functional test for the credentials acquisition.
 */
class CredentialsFunctionalTest extends Specification {
    @TempDir
    private File projectDir

    private getBuildFile() {
        new File( projectDir, "build.gradle" )
    }

    private getSettingsFile() {
        new File( projectDir, "settings.gradle" )
    }

    def "can run task"() {
        given:
        settingsFile << """
plugins {
    id  'nu.studer.credentials' version '3.0'
}

"""
//---> End of settings file <--------------------------------------------------

        buildFile << """
plugins {
    id  'nu.studer.credentials'
}

String gitUsername = credentials.forKey( 'tquadratGitHubUser' )
System.out.println( gitUsername )
String gitPassword = credentials.forKey( 'tquadratGitHubPassword' )
System.out.println( gitPassword )

task doSomething {
    doLast {
        println "Alive!"
    }
} 
"""
//---> End of build file <-----------------------------------------------------

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        var param = "-PcredentialsLocation=%s/.gradle".formatted( System.getProperty( "user.home" ) );
        runner.withArguments( param, "doSomething" )
        runner.withProjectDir( projectDir )
        def result = runner.build()

        then:
        result.output.contains( "Alive!" )
    }
}