/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.tquadrat.foundation.gradle.gitpublisher

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'org.tquadrat.foundation.gradle.gitpublisher.greeting' plugin.
 */
class GITPublisherPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.tquadrat.foundation.gradle.gitpublisher")

        then:
        project.tasks.findByName("publishToGIT") != null
    }
}